---
# tasks file for bootstrap
- name: wait for the host
  wait_for:
    port: "{{ ansible_port | default('22') }}"
    host: "{{ (ansible_ssh_host | default(ansible_host) | default(inventory_hostname)) }}"
  connection: local
  become: no
  when:
    - ansible_connection is defined
    - ansible_connection != "docker"
    - bootstrap_wait_for_host | bool

- name: test connection
  wait_for_connection:
    timeout: "{{ bootstrap_timeout }}"
  register: bootstrap_connect
  changed_when: no
  ignore_errors: yes

- name: register temporary bootstrap user
  set_fact:
    bootstrap_ansible_user: "{{ (ansible_user | default(omit, true))
                             if bootstrap_connect is succeeded else bootstrap_user }}"
  changed_when: no

- name: prepare system
  block:
    - name: register distribution
      include_tasks: register.yml

    - name: install bootstrap_packages
      include_tasks: install.yml
  when: bootstrap_connect is not succeeded

- name: support python3 on ansible <= 2.7
  block:
    - name: register local ansible version
      command: ansible --version
      register: bootstrap_ansible
      delegate_to: localhost
      changed_when: no
    - name: set ansible python interpreter
      set_fact:
        ansible_python_interpreter: "{{ '/usr/bin/python3' if 'python3' in bootstrap_packages else '/usr/bin/python' }}"
      when:
        - bootstrap_ansible.stdout|regex_replace('^ansible (\\d{1,2})(\\.\\d)?.*\n$', '\\1')|int <= 2
        - bootstrap_ansible.stdout|regex_replace('^ansible \\d{1,2}\\.(\\d{1,2})(\\.\\d)?.*\n$', '\\1')|int < 8

- name: ensure all bootstrap_packages are installed
  block:
    - name: gather facts
      setup:

    - name: install bootstrap_facts_packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ bootstrap_facts_packages.split() }}"
      register: bootstrap_install_bootstrap_facts_packages
      until: bootstrap_install_bootstrap_facts_packages is succeeded
      retries: 3
  vars:
    ansible_user: "{{ bootstrap_ansible_user | default(omit) }}"
