---
# tasks file for bootstrap
- name: wait for the host
  wait_for:
    port: "{{ ansible_port | default('22') }}"
    host: "{{ (ansible_ssh_host | default(ansible_host) | default(inventory_hostname)) }}"
  connection: local
  become: no
  when:
    - ansible_connection is defined
    - ansible_connection != "docker"
    - bootstrap_wait_for_host | bool

- name: prepare system
  block:
    - name: test connection
      wait_for_connection:
        timeout: "{{ bootstrap_timeout }}"
      register: bootstrap_connect
      changed_when: no
  rescue:
    - name: register temporary bootstrap user
      set_fact:
        bootstrap_ansible_user: "{{ bootstrap_user }}"
      changed_when: no
    - name: register distribution
      include_tasks: register.yml

    - name: install bootstrap_packages
      include_tasks: install.yml

    - name: set ansible_python_interpreter (ansible<2.8)
      set_fact:
        ansible_python_interpreter: "{{ '/usr/bin/python3' if 'python3' in bootstrap_packages else '/usr/bin/python' }}"
      changed_when: no
      when:
        - ansible_version.major <= 2
        - ansible_version.minor < 8

    - name: save ansible_python_interpreter (ansible<2.8)
      ini_file:
        path: /etc/ansible/facts.d/python.fact
        section: interpreter_python
        option: "{{ inventory_hostname }}"
        value: "{{ ansible_python_interpreter }}"
        mode: '0644'
      delegate_to: localhost
      when:
        - ansible_version.major <= 2
        - ansible_version.minor < 8

- name: ensure all bootstrap_packages are installed
  block:
    - name: gather facts
      setup:

    - name: install bootstrap_facts_packages
      package:
        name: "{{ item }}"
        state: present
      with_items: "{{ bootstrap_facts_packages.split() }}"
      register: bootstrap_install_bootstrap_facts_packages
      until: bootstrap_install_bootstrap_facts_packages is succeeded
      retries: 3
      when:
        - bootstrap_connect is succeeded
        - ansible_distribution is defined
  vars:
    ansible_user: "{{ bootstrap_ansible_user | default(omit) }}"
