---
- name: register package manager
  become: no
  check_mode: no
  block:
    - name: register Alpine
      raw: cat /etc/alpine-release
      register: alpine
      changed_when: no
      failed_when: no

    - name: set variables for Alpine
      set_fact:
        bootstrap_distribution: Alpine
        bootstrap_distribution_major_version: NA
      when:
        - alpine.rc == 0

    - name: register Amazon
      raw: test -f /etc/system-release && grep PRETTY_NAME /etc/os-release
      register: amazon
      changed_when: no
      failed_when: no

    - name: set variables for Amazon
      set_fact:
        bootstrap_distribution: "{{ amazon.stdout | regex_replace('^.*=.([a-zA-Z]*) .*\n$', '\\1') }}"
        bootstrap_distribution_major_version: "{{ amazon.stdout | regex_replace('^.* (\\d{2,3})(\\.\\d)?.*\n$', '\\1') }}"
      when:
        - amazon.rc == 0
        - amazon.stdout.find('Amazon') != -1

    - name: register Archlinux
      raw: test -f /etc/arch-release && cat /etc/os-release
      register: archlinux
      changed_when: no
      failed_when: no

    - name: set variables for Archlinux
      set_fact:
        bootstrap_distribution: Archlinux
        bootstrap_distribution_major_version: NA
      when:
        - archlinux.rc == 0

    - name: register Debian
      raw: test -f /etc/debian_version && grep PRETTY_NAME /etc/os-release
      register: debian
      changed_when: no
      failed_when: no

    - name: set variables for Debian
      set_fact:
        bootstrap_distribution: "{{ debian.stdout | regex_replace('^.*=.([a-zA-Z]*) .*\n$', '\\1') }}"
        bootstrap_distribution_major_version: "{{ debian.stdout | regex_replace('^.* (\\d{2,3})(\\.\\d)?.*\n$', '\\1') }}"
      when:
        - debian.rc == 0

    - name: register Gentoo
      raw: test -f /etc/gentoo-release
      register: gentoo
      changed_when: no
      failed_when: no

    - name: set variables for Gentoo
      set_fact:
        bootstrap_distribution: Gentoo
        bootstrap_distribution_major_version: NA
      when:
        - gentoo.rc == 0

    - name: register openSUSE
      raw: grep -qi "opensuse" /etc/os-release && grep PRETTY_NAME /etc/os-release
      register: opensuse
      changed_when: no
      failed_when: no

    - name: set variables for opensuse
      set_fact:
        bootstrap_distribution: "{{ opensuse.stdout | regex_replace('^.*=.([a-zA-Z]*) .*\n$', '\\1') }}"
        bootstrap_distribution_major_version: "{{ opensuse.stdout | regex_replace('^.* (\\d{2,3})(\\.\\d)?.*\n$', '\\1') }}"
      when:
        - opensuse.rc == 0

    - name: register Red Hat
      raw: cat /etc/redhat-release
      register: redhat
      changed_when: no
      failed_when: no

    - name: set variables for Red Hat
      set_fact:
        bootstrap_distribution: "{{ redhat.stdout.split(' release ')[0] }}"
        bootstrap_distribution_major_version: "{{ redhat.stdout.split(' release ')[1].split('.')[0] }}"
      when:
        - redhat.rc == 0

    - name: map distribution name
      set_fact:
        bootstrap_distribution: "{{ item.key }}"
      loop: "{{ bootstrap_distributions|dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      changed_when: no
      when: bootstrap_distribution|default('NA') in item.value
  vars:
    ansible_user: "{{ bootstrap_ansible_user | default(omit) }}"
