---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: molecule/.yamllint
platforms:
  # https://docs.aws.amazon.com/en_us/AWSEC2/latest/UserGuide/finding-an-ami.html
  - name: "${TEST_INSTANCE_PREFIX:-instance}_${TEST_DISTRO:-centos-latest}_${TOX_ENVNAME:-ec2}"
    image: ${TEST_EC2_AMI:-ami-dd3c0f36}
    instance_type: t2.micro
    vpc_subnet_id: ${TEST_EC2_VPC_SUBNET_ID:-""}
    root_device:
      device_name: ${TEST_EC2_ROOT_DEVICE:-""}
    groups:
      - ${TEST_DISTRO:-centos-latest}_ec2
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python${TOX_PYTHON_VERSION:-2.7}/site-packages/ara/plugins/callbacks
  playbooks:
    converge: ${TEST_PLAYBOOK:-../playbook.yml}
  inventory:
    group_vars:
      amazon-linux-2_ec2:
        bootstrap_user: ec2-user
      centos-latest_ec2:
        bootstrap_user: centos
      debian-latest_ec2:
        bootstrap_user: admin
      fedora-latest_ec2:
        bootstrap_user: fedora
      ubuntu-latest_ec2:
        bootstrap_user: ubuntu
scenario:
  name: ec2
verifier:
  name: goss
  directory: ../tests
  lint:
    name: yamllint
