---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  roles:
    - role: ansible-role-bootstrap

  tasks:
    - name: test connection
      ping:
      vars:
        ansible_user: "{{ bootstrap_ansible_user | default(omit) }}"
