---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: bootstrap-rhel-latest
    image: ubi8:latest
    registry:
      url: registry.access.redhat.com
      credentials:
        username: $redhatregistryusername
        password: $redhatregistrypassword
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbook.yml
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
  lint:
    name: ansible-lint
    options:
      exclude:
        - meta/version.yml
        - meta/exception.yml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: rhel-latest
